#!/bin/bash

# Adds a desktop entry for the current user

create_desktop_entry() {
	NAME="Popcorn Time"
	COMMENT="Watch Movies and TV Shows instantly!"

	CURRENT_DIR=$(pwd)
	EXECUTABLE=$CURRENT_DIR/Popcorn-Time
	ICON_PATH=$CURRENT_DIR/src/app/images/icon.png

	DESTINATION_DIR=/home/$(whoami)/.local/share/applications
	DESKTOP_FILE=$DESTINATION_DIR/popcorn-time.desktop

	echo "[Desktop Entry]" > $DESKTOP_FILE
	echo "Version=1.0" >> $DESKTOP_FILE
	echo "Type=Application" >> $DESKTOP_FILE
	echo "Name=$NAME" >> $DESKTOP_FILE
	echo "Icon=$ICON_PATH" >> $DESKTOP_FILE
	echo "Exec=\"$EXECUTABLE\" %U" >> $DESKTOP_FILE
	echo "Comment=$COMMENT" >> $DESKTOP_FILE
	echo "Categories=Multimedia;" >> $DESKTOP_FILE
	echo "Terminal=false" >> $DESKTOP_FILE

	# Updates the desktop entries
	gtk-update-icon-cache /usr/share/icons/hicolor

	echo "Desktop entry added for $(whoami)"
}

printf "Create a desktop entry for Popcorn Time for the current user ? (Y)es/(N)o: "
read input

if [ "$input" == "Y" ] || [ "$input" == "y" ]
then
	create_desktop_entry
else
	echo "Just execute ./Create-Desktop-Entry when you are ready to create a desktop entry for Popcorn Time"
fi
